### ISSUE TITLE
the dependency async in pacakge.json does not have a version

### ISSUE THREAD

**Issue by aprilandjan** [tomas/wmic#11]
Hi, sorry to bother! I noticed that the dependendy module `async` in `package.json` does not have an explicit version (see https://github.com/tomas/wmic/blob/master/package.json#L17) 

This makes some confusing when I tried to debug dependency problems. Should we add the explicit needed version?

**Comment by tomas** [comment]
Sure, please submit a PR

**Comment by jonaskgandersson** [comment]
Hi,
I get some problem with this as well, the generated npm_scrinkwrap file for the application I use also miss the version key for async under wmic, and my guess is that this is because the missing version in package.json. As I understands it the version is mandatory in package.json. What version of async is the wmic tested with?

**Comment by tomas** [comment]
It's been a long time since I ran these tests. Please submit a PR if you want this fixed. :)

**Comment by jonaskgandersson** [comment]
This issue can be closed now, see commit #12
